name: zkcrypto tests

on: [push, pull_request, workflow_dispatch]

env:
  C_KZG_4844_GIT_HASH: 'fbef59a3f9e8fa998bdb5069d212daf83d586aa5'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: "[zkcrypto] Tests (minimal preset)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast --test eip_4844 tests --features minimal-spec

      - name: "[zkcrypto] Tests (mainnet preset)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast

      - name: "[zkcrypto] Tests (mainnet preset, parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast --features parallel

      - name: "[zkcrypto] Clippy"
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path zkcrypto/Cargo.toml --all-targets --all-features -- -D warnings

      - name: "[zkcrypto] Formatting"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path zkcrypto/Cargo.toml -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path kzg-bench/Cargo.toml -- --check
